### ISSUE TITLE
Create Text-Note 

### ISSUE THREAD

**Issue by jujuhartmann** [jujuhartmann/capstone-project#4]
**Value statement**

As a Participant
I need to create a MarkerNote with text content
so that I can save information tied to a timestamp

**Description** 

Participant sees a button "create Note" and, upon clicking it, gets a form to input text and to save it as a Note. Each Note will store the text input as well as the user's ID and the timestamp of the initiation of the creation process, i.e. not the time of saving the Note is important but the time at which the user decided to create a Note.

**Acceptance criteria**

- [ ] "create Note"-button initiates process and shows form
- [ ] allow text input
- [ ] auto-escape markup
- [ ] auto-escape code from text input
- [ ] prohibit code execution from text input
- [ ] auto-assign order number to MarkerNote
- [ ] generate object on click of "save"-button
- [ ] timestamp matches time at initiation of process

**Tasks**
- [ ] build button "create Note"
- [ ] build form
- [ ] build save

**Size**

medium
