### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by jujuhartmann** [jujuhartmann/capstone-project#5]
**Tasks**
* [x] set up repo on GitHub
* [x] connect local to remote
* [ ]  create react app: npx create-react-app capstone-project, npm start
* [ ]  install styled components: npm install styled-components
* [ ]  install storybook: npx -p @storybook/cli sb init\n
* [ ]  install cypress when used for the first time: npm install cypress --save-dev
* [ ]  Initial commit
* [ ]  prettierrc
* [ ]  gitignore
* [ ]  Delete per default files in React
* [ ]  Create folder img or icons
* [ ]  Create folder components
* [ ]  Create folder services or hooks
* [ ]  Create folder pages
* [ ]  Delete images
* [ ]  Delete App.css, index.css (?)
* [ ]  Delete manifest.json (?)

**Size**
small
