### ISSUE TITLE
Create START-SESSION-VIEW

### ISSUE THREAD

**Issue by jujuhartmann** [jujuhartmann/capstone-project#7]
**Value statement**

As a Participant
I need to start a new Session with the relative timestamp of the current Session
so that I can relate my Markers to a Session and its timeline.

**Description** 

![v0 1 - Start Session View](https://user-images.githubusercontent.com/11661552/86469262-51b7b180-bd39-11ea-989a-ee2a29a5f075.png) 

Participant sees a "start Session" button. Upon clicking it, a Session is started and its clock/timer starts to run. The view switches to CREATE-MARKER-VIEW. In that view an "X"-button can be clicked to end the Session and return to the SESSION VIEW.

**Acceptance criteria**

- [ ] "start Session" button starts clock for Session
- [ ] "start Session" button switches to SESSION VIEW (where Markers are created)
- [ ] allow text input
- [ ] auto-escape markup
- [ ] auto-escape code from text input
- [ ] prohibit code execution from text input
- [ ] auto-assign order number to Marker
- [ ] generate object on click of "save"-button
- [ ] timestamp matches time at initiation of process

**Tasks**
- [ ] build button "create Note"
- [ ] build form
- [ ] build save

**Size**

medium
